# Generated by Django 4.2.5 on 2023-10-12 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.IntegerField(choices=[(1, 'Red'), (2, 'Green'), (3, 'Blue'), (4, 'Yellow'), (5, 'Orange')], unique=True)),
                ('user_color', models.CharField(default='1', max_length=100, unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_colors', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('user_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_user_color', to='taskmanager.colormodel', to_field='user_color')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_username', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
