# Generated by Django 4.2.5 on 2023-10-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormodel',
            name='color',
            field=models.IntegerField(choices=[(1, 'Red'), (2, 'Green'), (3, 'Blue'), (4, 'Yellow'), (5, 'Orange')]),
        ),
    ]
