# Generated by Django 4.2.5 on 2023-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_colormodel_username_alter_taskmodel_user_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
