# Generated by Django 4.2.5 on 2023-10-16 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0004_taskmodel_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_username', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
